export const CREATE_TODO = {
  START: "CREATE_TODO_START",
  SUCCESS: "CREATE_TODO_SUCCESS",
  FAILURE: "CREATE_TODO_FAILURE",
};

export const GET_TODOS = {
  START: "GET_TODOS_START",
  SUCCESS: "GET_TODO_SUCCESS",
  FAILURE: "GET_TODO_FAILURE",
};

export const DELETE_TODO = {
  START: "DELETE_TODO_START",
  SUCCESS: "DELETE_TODO_SUCCESS",
  FAILURE: "DELETE_TODO_FAILURE",
};

export const EDIT_TODO = {
  START: "EDIT_TODO_START",
  SUCCESS: "EDIT_TODO_SUCCESS",
  FAILURE: "EDIT_TODO_FAILURE",
};

export const CREATE_TAG = {
  START: "CREATE_TAG_START",
  SUCCESS: "CREATE_TAG_SUCCESS",
  FAILURE: "CREATE_TAG_FAILURE",
};

export const GET_TAGS = {
  START: "GET_TAGS_START",
  SUCCESS: "GET_TAGS_SUCCESS",
  FAILURE: "GET_TAGS_FAILURE",
};

export const DELETE_TAG = {
  START: "DELETE_TAG_START",
  SUCCESS: "DELETE_TAG_SUCCESS",
  FAILURE: "DELETE_TAG_FAILURE",
};

export const EDIT_TAG = {
  START: "EDIT_TAG_START",
  SUCCESS: "EDIT_TAG_SUCCESS",
  FAILURE: "EDIT_TAG_FAILURE",
};

export const ADD_SEARCH_TAG = "ADD_SEARCH_TAG";

export const REMOVE_SEARCH_TAG = "REMOVE_SEARCH_TAG";

export const GET_SEARCH_TAG = "GET_SEARCH_TAG";
